version: '3.11'
services:
  fastapi:
    build: .
    expose:
      -  "8000"
    command: >
      sh -c "pytest &&
            uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"


#  flask:
#    build:
#      context: .
#    env_file:
#      - .env
#    command: python Flask/main.py
#    ports:
#      - '5000:5000'
#    depends_on:
#      - postgres


#  postgres:
#    image: postgres:15-alpine
#    ports:
#      - '${DB_PORT}:5432'
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASS}
